### ISSUE TITLE
Install single app - confirm assumptions and implement

### ISSUE THREAD

**Issue by starsinmypockets** [JarvusInnovations/chaki#12]
I'm guessing the behavior here is to check the chaki.io api for the package and then download as normal. to the current project, or the --app specified project.

Should we add --save flag to add to project's app.json?

**Comment by themightychris** [comment]
Are you talking about a usage where you name a specific package from the command line (e.g. `chaki install jarvus-apikit`) rather than the bare `chaki install` command that installs all the app's existing deps?

**Comment by themightychris** [comment]
If so I'd say the default behavior should be adding the package to app.json, it's not usable for anything without that. There could be an optional flag then to disable that and one to specify exactly where to clone it to in case someone is doing something advanced

**Comment by starsinmypockets** [comment]
This is complicated by the fact that app.json is not in fact json - it includes comments, not part of the json spec! String parsing is kludgy and might not be reliable or portable since the format could change in a trivial way that breaks our implementation (adding a second example of the requires array in the comments, or removing it, etc)  - open to thoughts here!
