### ISSUE TITLE
Review package dependencies

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#14]
nodegit was left in package.json and doesn't appear to be needed, and i found that some required packages weren't present. Please audit every library that is `require`d in the app and ensure package.json's dependency list is up to date and have appropriate version restrictions

**Comment by starsinmypockets** [comment]
Not quite sure how to handle version restrictions. Should we >= current version, or should we lock down versions at current?

**Comment by themightychris** [comment]
Let's do `1.2.x` to grab the latest patch release of the current major+minor version

**Comment by starsinmypockets** [comment]
That makes perfect sense

**Comment by starsinmypockets** [comment]
Actually, maybe this is what we want:
https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by themightychris** [comment]
@starsinmypockets yeah let's go with that
