### ISSUE TITLE
Auto-select branch based on app's framework

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#2]
when grabbing a repo, chaki should look at all the available remote branches and if a framework and/or version-specific branch is available clone that instead of master

For example, if an app is touch 2.4.1.527, chaki would pick the first branch found of:
- touch/2.4.1.527
- touch/2.4.1
- touch/2.4
- touch/2
- touch
- master

**Comment by themightychris** [comment]
This logic is already implemented in the PHP chaki client: https://github.com/JarvusInnovations/chaki-emergence/blob/master/php-classes/Chaki/Package.php#L49

**Comment by starsinmypockets** [comment]
@themightychris This link is dead - If I could see the php implementation it would help :)

**Comment by themightychris** [comment]
@starsinmypockets oops the repo was private, it's public now
