### ISSUE TITLE
Convert to flatiron cli app

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#3]

**Comment by starsinmypockets** [comment]
flatiron might be overkill here. I've factored this into a self-contained app with a module structure that seems like it should be sufficient

**Comment by starsinmypockets** [comment]
@themightychris Let me know what the priority here is - probably the sooner we do it the less work it is... I like having control over the module structure, but I can see that flatiron provides a lot of conveniences and it doesn't look too opinionated

**Comment by themightychris** [comment]
move ahead on this at-will
