### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#5]

**Comment by starsinmypockets** [comment]
Gonna create a jarvus user, I guess - what email address should I use?
@themightychris

**Comment by themightychris** [comment]
use hello@jarv.us

On Thu, Aug 20, 2015 at 11:57 AM, Paul Walker <notifications@github.com>
wrote:

> Gonna create a jarvus user, I guess - what email address should I use?
> @themightychris <https://github.com/themightychris>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JarvusInnovations/chaki/issues/5#issuecomment-133059616>
> .
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166
