### ISSUE TITLE
Hook into app build process

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#6]
When running `chaki install` on an app, add a target hook into the app's build.xml to have it check for package updates or missing packages before each build

**Comment by starsinmypockets** [comment]
Just logging assumptions here - it looks from the docs like we need to update the xml directly, as opposed to using cmd / ant

**Comment by themightychris** [comment]
Yep, we'd have to append a snippet to define a -before-build target inside the app's build.xml. We could keep it pretty simple and pattern-based at first rather than going all-out with an XML parses/writer.

**Comment by starsinmypockets** [comment]
I found a node lib that doesn't require a binary

**Comment by themightychris** [comment]
For what, parsing XML?

On Thu, Aug 20, 2015 at 4:49 PM, Paul Walker <notifications@github.com>
wrote:

> I found a node lib that doesn't require a binary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JarvusInnovations/chaki/issues/6#issuecomment-133166746>
> .
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166
