### ISSUE TITLE
Send hash of app id in header when fetching package details from chaki.io

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/chaki#9]
app.json contains a randomly generated GUID that's unique to each app. When making the GET request against chaki.io before grabbing a dependent package, pass a SHA1 hash of the GUID in a header somewhere. Might make sense to put that in the User-Agent header.

We will use this header server-side to identify how many distinct applications have pulled each package and provide popularity statistics.

**Comment by starsinmypockets** [comment]
OK, I add a AppId header with the uuid...

I don't have a good way set up to test the outbound api calls at the moment - might be easiest to just take a look at this from the chaki.io end before releasing

**Comment by starsinmypockets** [comment]
12:28:29.975725 IP (tos 0x0, ttl 64, id 19234, offset 0, flags [DF], proto TCP (6), length 288)
    li325-20.members.linode.com.44790 > clients01.jarv.us.http: Flags [P.], cksum 0xdcc4 (incorrect -> 0x0f36), seq 2639420331:2639420567, ack 1897399132, win 229, options [nop,nop,TS val 354095243 ecr 4078108073], length 236
E.. K"@.@...B.,........P.R[.q..\...........
........GET /packages/chaki-test-module-B HTTP/1.1
Accept: application/json
User-Agent: Restler for node.js
Host: chaki.io
Accept-Encoding: gzip, deflate
**AppId: e21d2a04-1fe0-4793-a299-186188656a28**
Content-Length: 0
Connection: close

**Comment by themightychris** [comment]
Looks good, but its bad practice to set nonstandard headers without
prefixing them with X-

I wanted this to be hashed though and put inside the User-Agent header.
Lets do something like:

User-Agent: Chaki/0.0.2 (ext/5.1.1.451; app/APP_GUID_SHA1)

Here's an example of how you can read a package's own metadata to
dynamically get the chaki version:
https://github.com/JarvusInnovations/Emergence/blob/releases/0.0.3/kernel-lib/server.js#L84

On Thu, Aug 20, 2015 at 8:33 AM, Paul Walker <notifications@github.com>
wrote:

> 12:28:29.975725 IP (tos 0x0, ttl 64, id 19234, offset 0, flags [DF], proto
> TCP (6), length 288)
> li325-20.members.linode.com.44790 > clients01.jarv.us.http: Flags [P.],
> cksum 0xdcc4 (incorrect -> 0x0f36), seq 2639420331:2639420567, ack
> 1897399132, win 229, options [nop,nop,TS val 354095243 ecr 4078108073],
> length 236
> E.. K"@.@...B.,........P.R[.q.............
> ........GET /packages/chaki-test-module-B HTTP/1.1
> Accept: application/json
> User-Agent: Restler for node.js
> Host: chaki.io
> Accept-Encoding: gzip, deflate
> *AppId: e21d2a04-1fe0-4793-a299-186188656a28*
> Content-Length: 0
> Connection: close
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JarvusInnovations/chaki/issues/9#issuecomment-132992479>
> .
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166

**Comment by starsinmypockets** [comment]
Here from the raw output...

Accept: application/json
User-Agent: Chaki/0.0.1 (ext/5.1.1.451); app/6685959d49d40933cd426b016c5ed978759b414d
Host: chaki.io
Accept-Encoding: gzip, deflate

**Comment by themightychris** [comment]
the closing paren should be at the end like in my example

On Thu, Aug 20, 2015 at 1:01 PM, Paul Walker <notifications@github.com>
wrote:

> Here from the raw output...
>
> Accept: application/json
> User-Agent: Chaki/0.0.1 (ext/5.1.1.451);
> app/6685959d49d40933cd426b016c5ed978759b414d
> Host: chaki.io
> Accept-Encoding: gzip, deflate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JarvusInnovations/chaki/issues/9#issuecomment-133077095>
> .
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166

**Comment by starsinmypockets** [comment]
Chaki/0.0.1 (ext/5.1.1.451; app/6685959d49d40933cd426b016c5ed978759b414d)
